### PR TITLE
Update active Cemu account when switching BCML profiles

### PR DESCRIPTION
**Pull request by jacobjmarks**
This PR aims to simplify the process of coupling a BCML profile to a respective Cemu account.

These changes see the addition of a new configuration option which, when active, will update the active Cemu account when switching BCML profiles to the account with a matching Mii name (case insensitive), if one exists.

### Background

Scenario: Two users using the same BCML/Cemu instance want to each have their own BCML profile (for mod selection) and Cemu account (for save game, etc.).

The current approach requires two steps across two applications:
1. Open BCML and change the active profile
2. Open Cemu (if not already) and change the active account
3. Launch game

Revised workflow:
1. Open BCML and change the active profile
   - BCML will update the Cemu account to match
3. Launch game (via BCML)

### Known issues

- #### Account switch does not stick when Cemu is running

  Cemu, when running, seems to maintain its own `settings.xml` state which it rewrites when performing certain activities like launching a game or closing the application. Despite BCML having no issues in updating the stated active account within the settings file, if the prior Cemu application instance is utilised, the account change will be ignored.

  Note that when launching an _additional_ Cemu instance via BCML (_Launch Game_), the account switch is correctly reflected within that new instance (as it took the updated `settings.xml` state upon launch).

### CODE REVIEW

**Comment by jacobjmarks** [comment]
Hmm. An alternative approach here to avoid the "flaky" account persistence when a Cemu instance is already running (as described in _Known issues_ above) would be to simply tie the account switching to BCML's _Launch Game_ feature via the `cemu.exe --account` flag. This will also alleviate the need to modify Cemu's `settings.xml` altogether. Obvious caveat would be that the account switch would not persist when launching Cemu separately, but I don't think this would be an issue at all.

**Comment by jacobjmarks** [comment]
I have revised the PR to utilise cemu launch args to set the active profile as described above. Feedback here would be much appreciated.

Outstanding:
- Factor new setting name and UI elements to reflect new logic
- Add new setting to `src/settings.rs`?

**Comment by GingerAvalanche** [comment]
Using launch arguments may not be the wisest thing, as many windows users can't utilize the button to launch cemu, due to a series of permissions issues.

Users might also not use the same name for the account as they would for the profile. It might be a better idea to have an account name field attached to the profile in bcml.

**Comment by jacobjmarks** [comment]
I see. Yes, perhaps associating the account (via the persistent ID) with the profile directly will be a little more robust; and would alleviate the necessity for the account's Mii name to match that of the BCML profile (as well as the added resiliency if the Mii name is changed). I'll be away for a week but am keen to return to this.

Current WIP:

image

**Comment by jacobjmarks** [comment]
Are there any concerns regarding the "sticky" settings issue when updating Cemu's `settings.xml` file while a Cemu instance is running? Is this something with should actively try cater for? Or will something like a caveat suffice.

I've been utilising the account switching via the launch arguments (as is the current state of this PR) which has been working very well but I can definitely get behind your point on the fact that ideally, features shouldn't require that the game be launched via BCML.

I can see the following options:

Associating BCML profile with Cemu account:
- Option A: ~Automated association if BCML profile name matches Cemu account Mii name~
- Option B: Ability to manually associate Cemu account with BCML profile (example/WIP in my previous comment)

Actually utilising the associated Cemu account:
- Option A: Use via BCML's Cemu launch arguments
    - Add caveat that this feature is only suitable when launching Cemu via BCML
- Option B: Modify Cemu's `settings.xml` (preferred)
    - Change is only respected for _new_ instances of Cemu[^1] (add a caveat for this?)

[^1]: Ideally, there would be a workaround/fix for this; such that this change is respected whether or not an instance of Cemu is running.

**Comment by jacobjmarks** [comment]
@NiceneNerd not sure if you've read through this one; any thoughts on this topic?

**Comment by GingerAvalanche** [comment]
Cemu reads its settings file once on bootup, and then keeps the settings in memory, and writes them out whenever it feels like it. The only workaround that doesn’t involve manipulating the memory allocated by the Cemu instance is to just have the user not leave Cemu open when doing BCML things. I wouldn’t want to do this, due to data privacy concerns, but it is possible to scan the open process list for cemu.exe and warn the user it’s open.

**Comment by jacobjmarks** [comment]
Closing as I have stopped working on this 😅

**Pull request closed without merging**
