### PR TITLE
Changed install_mod encoding

### PR DESCRIPTION
**Pull request by Lvieira21**
Changed encoding during load-up of mod file in order to enable Portuguese (Brazilian) mods to be installed

### CODE REVIEW

**Comment by GingerAvalanche** [comment]
Is iso8859-1 an extension of utf-8? Many mods have already been made with utf-8, so if iso8859-1 doesn’t include all of utf-8 inside it, this would break parsing those mods’ data.

Did you test this with other existing mods to make sure it was compatible with them?

**Comment by NiceneNerd** [comment]
That's my question as well. I'd be very concerned about switching willy nilly away from UTF-8 unless the alternative is guaranteed to support all the same characters besides whatever it adds.

**Comment by Lvieira21** [comment]
Sorry for giving little to no context, I got caught up at work.
So, I made this change because I was having some issues with the brazilian translation Mod, I was constantly getting 'UnicodeDecodeError'.
After changing the encoding, I tried reinstalling the translation mod and it worked fine. Then I made sure to reinstall the mods that I already had, and it did work as well. 
There's the list of mods I tried:
Hyrule Rebalanced 7.8
Armor description
Xbox One UI
HD Fonts
HD Icons and Maps
Links House Reworked
End Game Nightmare Mode

**Comment by NiceneNerd** [comment]
From what I can see from initial investigation, ISO-8859-1 mostly supports only Western languages, and not all of them completely. So on the whole it is less widely compatible than UTF-8.

Moreover, as Ginger noted, encoding is specified in several places across BCML, very many more than just when the `info.json` is loaded. This fix would not affect any of those other places and thus could still error out on some Portuguese characters, but some of those places definitely need to have UTF-8 for Japanese support.

So for now I don't think switching is a viable option.

**Comment by Lvieira21** [comment]
I didn't change anywhere else cause I didn't see the need, since the other parts are writing in current working documents such as rules.txt and settings.xml.
Got it, no problem

**Comment by GingerAvalanche** [comment]
It’s likely that info.json is all that needs this kind of change. All game files either aren’t text or have to be UTF-8 or UTF-16 by hard-coding, and all log files follow the same rules in order to be copyable into game files, so it’s really only info.json and options.json, I think?

If you think this is an issue worth pursuing (as you could always edit the bnp to get rid of the description in info.json, and it’d work, but that’s still kind of an annoying workaround) then it might be worth making an enum to define encoding types, and then storing a value of that enum in a metadata file which is read before info.json or options.json and can then be used to determine which encoding is used to read them.

**Comment by Lvieira21** [comment]
Yup, Ginger, that makes sense.
And, coming to a sense, it is only one mod that demands this change, I don't think that would be a very smart.
Could compromise a lot of the already created mods, it would be easier and less harmful to try to fix the mod, instead of the manager.

**Pull request closed without merging**
