### PR TITLE
Update Havok Converter

### PR DESCRIPTION
**Pull request by ArchLeaders**
This updates the Havok converter in `dev._convert_actorpack` to use the new C# [havok converter tool](https://github.com/krenyy/HKXConvert) made by kreny, which fixed several issues with the converted Havok files.

### CODE REVIEW

**Comment by ArchLeaders** [comment]
Seems to cause some cross-threading issues where the process doesn't release the file at the right time. Not really sure how the rest of the process works, but hold off on merging this until I figure out a way to fix it ~and/or just finish my designated converter~.

**Comment by GingerAvalanche** [comment]
If it helps, this is actually two errors:
- the first is that there’s no differentiation made between files in different actor packs, so same-named files from different actor packs are put into the same location. This means only the first file of any given name will be diffed by BCML. (Note that this is not a problem because same-named files with different data aren’t supported by BotW, but it does feed into the second error)
- the second error is that the file location is logged for deletion multiple times. Since the file is only written once, it can only be deleted once, and the attempt to delete it the second time causes the fatal error.

You should be able to fix this rather easily by checking if a file of the name exists already in the temp folder, and if so, not converting it or logging the path for deletion.

Another option would be storing them with the actor pack name at the beginning of the path, thus making the path unique for each file. This would recreate the original mod’s files more accurately in the final merge, but would be slower and wouldn’t really matter, since the game would discard a version of the file when another was already in memory, anyway

**Comment by ArchLeaders** [comment]
> Another option would be storing them with the actor pack name at the beginning of the path, thus making the path unique for each file. This would recreate the original mod’s files more accurately in the final merge, but would be slower and wouldn’t really matter, since the game would discard a version of the file when another was already in memory, anyway

This should already be done, which is why this error confuses me.

Also I don't think either error comes from BCML's old converter code. The first one is HKXConverter throwing an error instead of just overwriting the file (for some reason); and the second error isn't trying to delete the file, it's attempting to read it back into memory because it's converted with a subprocess and written to the drive (not ideal, but Idk how to use pythonnet to interop the DLL instead).

**Comment by GingerAvalanche** [comment]
> This should already be done, which is why this error confuses me, there are very few ways I can find that would cause this error to occur.

It's not done. You can tell because the error has the path without the actor pack name in it.

> Also, unless I'm missing something here, I don't think either error comes from BCML's old converter code. The first one is HKXConverter throwing an error instead of just overwriting the file (for some reason), and the second error isn't trying to delete the file, it's attempting to read it back into memory because it's converted with a subprocess, and written to the drive (not ideal, but Idk how to use pythonnet to interop the DLL instead).

Also incorrect, you can tell because the code throwing the error is `hk_file.unlink()`, and `.unlink()`'s purpose is to delete a file. (or, more specifically, to disable to link to the data location on the drive, which is what actually happens when we delete files)

**Comment by ArchLeaders** [comment]
> > **This should already be done**, which is why this error confuses me, there are very few ways I can find that would cause this error to occur.
> 
> It's not done. You can tell because the error has the path without the actor pack name in it.

It's at the end here. Are you saying I should put it in the root folder (`hk_convert/{actor_name}`) as well?
image

> > Also, unless I'm missing something here, I don't think either error comes from BCML's old converter code. The first one is HKXConverter throwing an error instead of just overwriting the file (for some reason), and **the second error isn't trying to delete the file, it's attempting to read it back into memory** because it's converted with a subprocess, and written to the drive (not ideal, but Idk how to use pythonnet to interop the DLL instead).
> 
> Also incorrect, you can tell because the code throwing the error is `hk_file.unlink()`, and `.unlink()`'s purpose is to delete a file. (or, more specifically, to disable the link between the file table and the data location on the drive, which is what actually happens when we delete files)

Huh, I could have sworn I saw the other call in that error at some point. Oh well, thanks for pointing that out. ~I'll hopefully learn to read sometime soon.~

**Comment by ArchLeaders** [comment]
> > It's at the end here. Are you saying I should put it in the root folder (`hk_convert/{actor_name}`) as well? image
> 
> There is no actor in the game named Enemy_Bokoblin. That is just the name of a folder that is inside the actor pack that is shared among most Enemy_Bokoblin_something actors - Enemy_Bokoblin_Junior, Enemy_Bokoblin_Senior, Enemy_Bokoblin_Middle, Enemy_Bokoblin_Dark, etc. image

Ah, I see. Thanks.

(also any reason editing my post instead of commenting?)

**Comment by GingerAvalanche** [comment]
>It's at the end here. Are you saying I should put it in the root folder (`hk_convert/{actor_name}`) as well? image

There is no actor in the game named Enemy_Bokoblin. That is just the name of a folder that is inside the actor pack that is shared among most Enemy_Bokoblin_something actors - Enemy_Bokoblin_Junior, Enemy_Bokoblin_Senior, Enemy_Bokoblin_Middle, Enemy_Bokoblin_Dark, etc.
image

**Comment by GingerAvalanche** [comment]
@ArchLeaders Sorry, I forgot this issue existed.

Have you tried only converting if the file doesn't already exist, and then unlinking at the end of the process, after the pool has been joined and there's only one thread running? All files of the same name will have the same data, as defined by the game, so only converting a file once and then using that conversion in all places it's needed is sufficient.

That being said, I do wonder about the error's persistence - if you added the actor name as a folder at the beginning of the path, the error *could* not persist, due to the fact that each actor name is unique, so each path would only exist once, and so would only be manipulated by one thread.

**Comment by ArchLeaders** [comment]
@GingerAvalanche think you can review this one more time? I tested through Nitram's converter, on mods that threw errors before, and both ran through BCML's converter successfully.

**Comment by NiceneNerd** [comment]
I do have some concerns about adding 30-45MB binaries to the BCML download. The wheels are already quite large and creating issues with PyPI.

**Comment by ArchLeaders** [comment]
Hmm, yeah, that is a little concerning. I wonder if it might be better to just skip Havok conversion entirely and let Nitram's converter handle it instead.

**Comment by GingerAvalanche** [comment]
Works for me. I think, with the ultimate converter's existence, we could probably even remove the conversion option from BCML entirely. The logic isn't that complicated, and could be reimplemented in the ultimate converter.

Not that that needs to happen, it just seems odd to me that BCML is both a tool and a library API. Makes sense to have a callable API for `M`od `L`oader things, since it's in the name, but eh.

Anyway, with Nicene pointing out that this would increase the package size by 81MB (and it's 37MB right now, so that'd be a hefty increase) I vote to close this.

**Comment by ArchLeaders** [comment]
Alright sounds good.

As for un-implementing the converter, I think that's kind of pointless at this point of BCML's lifespan, but I do plan on completely re-implementation a mod converter in C# that won't interact with BCML (or anything external for that matter) at all.
So before that happens (which could/will be a while), it'll probably be best to leave both converters alone (besides getting it back to what it was with Havok stuff) and wait for the new converter.

**Pull request closed without merging**
